### PR TITLE
Fix qsignature

### PR DESCRIPTION
**Pull request by vladsavelyev**
Bcbio outputs the file as `qsignature.ma`, fixing the regex so MultIQC picks it up.

### CODE REVIEW

**Comment by vladsavelyev** [comment]
Ah, just noticed that qsignature is commented out in multiqc_bcbio: https://github.com/MultiQC/MultiQC_bcbio/blob/master/multiqc_bcbio/bcbio.py#L85
It's not ready yet?

**Comment by chapmanb** [comment]
Thanks Vlad. I'm not positive about the status of this. @lpantano do you know if qsignature in multiqc is ready to go or do we need to work on it more?

**Comment by vladsavelyev** [comment]
Fixed a few things in the existing code for qsignature, and I think it looks okay now. Can be merged unless Lorena has any objections!

screen shot 2018-12-03 at 18 12 56

**Comment by lpantano** [comment]
Thanks! sorry I couldn't lool at this on Friday.

**Comment by vladsavelyev** [comment]
Thanks for merging!

**Pull request merged**
